### ISSUE TITLE
Update versions of applications?

### ISSUE THREAD

**Issue by edeandrea** [RedHat-Middleware-Workshops/cloud-native-workshop-v2m2-labs#2]
The catalog app is using Spring Boot 1.5.8 which is from 2017 and considered EOL by the Spring community. Shouldn't we make this more current?

Also the monolith is using the EAP 7.0 images. Shouldn't this be more current as well (EAP 7.2)?

**Comment by danieloh30** [comment]
EAP is now 7.2 image and SB is also 2.1.6.
